# $Id: Makefile 4116 2025-01-27 10:46:18Z jkoshy $

TOP = ..

SUBDIR =
SUBDIR+= atf			# ATF based test suites.
SUBDIR+= custom			# Test suites using custom frameworks.
SUBDIR+= tet			# TET based test suites.

SUBDIR+= libtest

.include "${TOP}/mk/elftoolchain.subdir.mk"
