# $Id: Makefile 4112 2025-01-27 10:41:15Z jkoshy $

TOP=		../../../..

SUBDIR+=	builtin
SUBDIR+=	misc
SUBDIR+=	qualifiers
SUBDIR+=	regression
SUBDIR+=	substitute
SUBDIR+=	template

.include "${TOP}/mk/elftoolchain.subdir.mk"
