# $Id: Makefile 4181 2025-02-12 15:17:52Z jkoshy $

TOP=		../../../..
SUBDIR=
SUBDIR+=	elftc_bfd_target
SUBDIR+=	elftc_get_machine_name
SUBDIR+=	elftc_get_relocation_type_name
SUBDIR+=	elftc_string_table
SUBDIR+=	elftc_version

.include "${TOP}/mk/elftoolchain.subdir.mk"
