# $Id: Makefile 4111 2025-01-27 10:39:10Z jkoshy $
#
# Examples of tests built using test(3).

TOP=	../../..

NOMAN=		true

CFLAGS+=	-I../lib -Wall -pedantic

TEST_SRCS=	minimal_example.c \
		simple_example.c

.include "$(TOP)/mk/elftoolchain.test.mk"
